[package]
name = "Rust_Capture"
version = "1.5.0"
edition = "2021"  # Use the latest edition of Rust

[dependencies]
anyhow = "1.0"    # For error handling
chrono = "0.4"    # For timestamp formatting
nix = "0.26"      # For process signaling
